// GENERATED by tools/gen-redirect-functions.py from tools/legacy-redirects.json - do not edit by hand.
// Legacy URL /blog/blogs/elkin-button-trap-spam-hurricane -> /blog/blogs/the-elkin-button-trap-why-that-click-here-discount-is-actually-a-spam-hurricane (edge 301; replaces the old meta-refresh stub).
const TO = "/blog/blogs/the-elkin-button-trap-why-that-click-here-discount-is-actually-a-spam-hurricane";
export function onRequest({ request, next }) {
  const url = new URL(request.url);
  // A function route also matches its trailing-slash twin. If that twin IS the
  // destination (e.g. /contact-us -> /contact-us/), serve the real page.
  if (url.pathname === TO) return next();
  return Response.redirect(new URL(TO + url.search, url.origin).toString(), 301);
}
