// GENERATED by tools/gen-redirect-functions.py from tools/legacy-redirects.json - do not edit by hand.
// Legacy URL /blog/blogs/nc-car-insurance-rates-rising-2026-national-premiums-drop -> /blog/blogs/why-are-north-carolina-car-insurance-rates-rising-in-2026-while-national-premiums-drop (edge 301; replaces the old meta-refresh stub).
const TO = "/blog/blogs/why-are-north-carolina-car-insurance-rates-rising-in-2026-while-national-premiums-drop";
export function onRequest({ request, next }) {
  const url = new URL(request.url);
  // A function route also matches its trailing-slash twin. If that twin IS the
  // destination (e.g. /contact-us -> /contact-us/), serve the real page.
  if (url.pathname === TO) return next();
  return Response.redirect(new URL(TO + url.search, url.origin).toString(), 301);
}
