// GENERATED by tools/gen-redirect-functions.py from tools/legacy-redirects.json - do not edit by hand.
// Legacy URL /blog/blogs/nc-fire-hydrant-home-insurance-2026 -> /blog/blogs/how-much-does-a-fire-hydrant-within-1000-feet-save-on-nc-home-insurance-in-2026 (edge 301; replaces the old meta-refresh stub).
const TO = "/blog/blogs/how-much-does-a-fire-hydrant-within-1000-feet-save-on-nc-home-insurance-in-2026";
export function onRequest({ request, next }) {
  const url = new URL(request.url);
  // A function route also matches its trailing-slash twin. If that twin IS the
  // destination (e.g. /contact-us -> /contact-us/), serve the real page.
  if (url.pathname === TO) return next();
  return Response.redirect(new URL(TO + url.search, url.origin).toString(), 301);
}
