// GENERATED by tools/gen-redirect-functions.py from tools/legacy-redirects.json - do not edit by hand.
// Legacy URL /blog/blogs/nc-holiday-burglaries-2025 -> /blog/blogs/nc-ranks-9th-for-holiday-burglaries-how-to-secure-your-gifts-before-the-big-day (edge 301; replaces the old meta-refresh stub).
const TO = "/blog/blogs/nc-ranks-9th-for-holiday-burglaries-how-to-secure-your-gifts-before-the-big-day";
export function onRequest({ request, next }) {
  const url = new URL(request.url);
  // A function route also matches its trailing-slash twin. If that twin IS the
  // destination (e.g. /contact-us -> /contact-us/), serve the real page.
  if (url.pathname === TO) return next();
  return Response.redirect(new URL(TO + url.search, url.origin).toString(), 301);
}
