// GENERATED by tools/gen-redirect-functions.py from tools/legacy-redirects.json - do not edit by hand.
// Legacy URL /blog/blogs/nc-insurance-check-lower-than-body-shop-estimate-2026 -> /blog/blogs/why-is-my-2026-nc-insurance-check-lower-than-the-elkin-body-shops-estimate (edge 301; replaces the old meta-refresh stub).
const TO = "/blog/blogs/why-is-my-2026-nc-insurance-check-lower-than-the-elkin-body-shops-estimate";
export function onRequest({ request, next }) {
  const url = new URL(request.url);
  // A function route also matches its trailing-slash twin. If that twin IS the
  // destination (e.g. /contact-us -> /contact-us/), serve the real page.
  if (url.pathname === TO) return next();
  return Response.redirect(new URL(TO + url.search, url.origin).toString(), 301);
}
