// GENERATED by tools/gen-redirect-functions.py from tools/legacy-redirects.json - do not edit by hand.
// Legacy URL /blog/blogs/nc-older-car-insurance-premiums-2025 -> /blog/blogs/north-carolina-auto-insurance-mystery-solved-why-your-older-cars-premiums-keep-climbing (edge 301; replaces the old meta-refresh stub).
const TO = "/blog/blogs/north-carolina-auto-insurance-mystery-solved-why-your-older-cars-premiums-keep-climbing";
export function onRequest({ request, next }) {
  const url = new URL(request.url);
  // A function route also matches its trailing-slash twin. If that twin IS the
  // destination (e.g. /contact-us -> /contact-us/), serve the real page.
  if (url.pathname === TO) return next();
  return Response.redirect(new URL(TO + url.search, url.origin).toString(), 301);
}
