// GENERATED by tools/gen-redirect-functions.py from tools/legacy-redirects.json - do not edit by hand.
// Legacy URL /blog/blogs/oh-deer-december-nc-drivers-2025 -> /blog/blogs/oh-deer-why-december-is-the-most-dangerous-month-for-nc-drivers (edge 301; replaces the old meta-refresh stub).
const TO = "/blog/blogs/oh-deer-why-december-is-the-most-dangerous-month-for-nc-drivers";
export function onRequest({ request, next }) {
  const url = new URL(request.url);
  // A function route also matches its trailing-slash twin. If that twin IS the
  // destination (e.g. /contact-us -> /contact-us/), serve the real page.
  if (url.pathname === TO) return next();
  return Response.redirect(new URL(TO + url.search, url.origin).toString(), 301);
}
