// GENERATED by tools/gen-redirect-functions.py from tools/legacy-redirects.json - do not edit by hand.
// Legacy URL /blog/blogs/winter-weather-advisory-surry-county-2025 -> /blog/blogs/winter-weather-advisory-in-surry-county-is-your-home-ready-for-freezing-rain (edge 301; replaces the old meta-refresh stub).
const TO = "/blog/blogs/winter-weather-advisory-in-surry-county-is-your-home-ready-for-freezing-rain";
export function onRequest({ request, next }) {
  const url = new URL(request.url);
  // A function route also matches its trailing-slash twin. If that twin IS the
  // destination (e.g. /contact-us -> /contact-us/), serve the real page.
  if (url.pathname === TO) return next();
  return Response.redirect(new URL(TO + url.search, url.origin).toString(), 301);
}
