// GENERATED by tools/gen-redirect-functions.py from tools/legacy-redirects.json - do not edit by hand.
// Legacy URL /10-ways-to-save-on-nc-car-insurance/ -> /blog/blogs/7-proven-ways-to-fight-rising-nc-auto-insurance-costs-a-guide-by-bill-layne-insurance (edge 301; replaces the old meta-refresh stub).
const TO = "/blog/blogs/7-proven-ways-to-fight-rising-nc-auto-insurance-costs-a-guide-by-bill-layne-insurance";
export function onRequest({ request, next }) {
  const url = new URL(request.url);
  // A function route also matches its trailing-slash twin. If that twin IS the
  // destination (e.g. /contact-us -> /contact-us/), serve the real page.
  if (url.pathname === TO) return next();
  return Response.redirect(new URL(TO + url.search, url.origin).toString(), 301);
}
