// GENERATED by tools/gen-redirect-functions.py from tools/legacy-redirects.json - do not edit by hand.
// Legacy URL /blog/turn-in-nc-license-plates-before-canceling-insurance/ -> /blog/blogs/why-north-carolina-makes-you-turn-in-your-tag-before-you-cancel-car-insurance (edge 301; replaces the old meta-refresh stub).
const TO = "/blog/blogs/why-north-carolina-makes-you-turn-in-your-tag-before-you-cancel-car-insurance";
export function onRequest({ request, next }) {
  const url = new URL(request.url);
  // A function route also matches its trailing-slash twin. If that twin IS the
  // destination (e.g. /contact-us -> /contact-us/), serve the real page.
  if (url.pathname === TO) return next();
  return Response.redirect(new URL(TO + url.search, url.origin).toString(), 301);
}
