// GENERATED by tools/gen-redirect-functions.py from tools/legacy-redirects.json - do not edit by hand.
// Legacy URL /blog/when-to-drop-collision-coverage-nc/ -> /blog/blogs/what-is-collision-coverage-in-nc-a-north-carolina-drivers-essential-guide (edge 301; replaces the old meta-refresh stub).
const TO = "/blog/blogs/what-is-collision-coverage-in-nc-a-north-carolina-drivers-essential-guide";
export function onRequest({ request, next }) {
  const url = new URL(request.url);
  // A function route also matches its trailing-slash twin. If that twin IS the
  // destination (e.g. /contact-us -> /contact-us/), serve the real page.
  if (url.pathname === TO) return next();
  return Response.redirect(new URL(TO + url.search, url.origin).toString(), 301);
}
