#!/usr/bin/env python3
"""
build-nav.py - inject the canonical site navigation into pages that need it.

Source of truth:  tools/nav.json
Styles:           css/bli-nav.css  (self-contained, namespaced .blinav-*)

The generated markup lives between the markers

    <!-- BLI-NAV:START ... -->   ...   <!-- BLI-NAV:END -->

so a re-run replaces it in place and is idempotent. Nothing outside the
markers is touched except one <link> tag in <head>, which is also marked.

Usage
    python tools/build-nav.py                 # dry run over wave 1, prints a diff
    python tools/build-nav.py --apply         # write wave 1
    python tools/build-nav.py --wave 1 --apply
    python tools/build-nav.py --pages a.html b.html --apply
    python tools/build-nav.py --check         # exit 1 if any page is out of date

Every substitution asserts it matched exactly once; on any mismatch the file is
left untouched and the page is reported as FAILED. Run without --apply first
and read the diff - this repo is the live site.
"""

import argparse
import difflib
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NAV_JSON = os.path.join(ROOT, 'tools', 'nav.json')

START = '<!-- BLI-NAV:START - generated by tools/build-nav.py from tools/nav.json. Do not edit by hand. -->'
END = '<!-- BLI-NAV:END -->'
CSS_START = '<!-- BLI-NAV-CSS:START -->'
CSS_END = '<!-- BLI-NAV-CSS:END -->'

BLOCK_RE = re.compile(
    re.escape(START) + r'.*?' + re.escape(END), re.S)
CSS_RE = re.compile(
    re.escape(CSS_START) + r'.*?' + re.escape(CSS_END), re.S)

ICON_PHONE = ('<svg viewBox="0 0 512 512" aria-hidden="true"><path d="M497.4 361.8l-112-48a24 24 0 0 0-28 6.9l-49.6 60.6A370.7 370.7 0 0 1 130.6 204.1l60.6-49.6a23.9 23.9 0 0 0 6.9-28l-48-112A24.2 24.2 0 0 0 122.6.6l-104 24A24 24 0 0 0 0 48c0 256.5 207.9 464 464 464a24 24 0 0 0 23.4-18.6l24-104a24.3 24.3 0 0 0-14-27.6z"/></svg>')
ICON_BOLT = ('<svg viewBox="0 0 320 512" aria-hidden="true"><path d="M296 160H180.6l42.6-129.8C227.2 17.9 218.1 0 204.2 0H96c-9.8 0-18.2 7.1-19.8 16.8l-48 288C26.2 316.8 35.4 328 47.6 328h118.7L119 480.2c-3.8 12.3 5.5 24 18.3 24 6.8 0 13.3-3.5 16.9-9.8l160-272c9.3-15.9-2.2-35.9-18.2-35.9z"/></svg>')
ICON_BARS = ('<svg viewBox="0 0 448 512" aria-hidden="true"><path d="M16 132h416c8.8 0 16-7.2 16-16V76c0-8.8-7.2-16-16-16H16C7.2 60 0 67.2 0 76v40c0 8.8 7.2 16 16 16zm0 160h416c8.8 0 16-7.2 16-16v-40c0-8.8-7.2-16-16-16H16c-8.8 0-16 7.2-16 16v40c0 8.8 7.2 16 16 16zm0 160h416c8.8 0 16-7.2 16-16v-40c0-8.8-7.2-16-16-16H16c-8.8 0-16 7.2-16 16v40c0 8.8 7.2 16 16 16z"/></svg>')

# Deliberately does NOT use requestAnimationFrame to kick off the transition:
# rAF does not fire while the page is not being painted (background tab, an
# occluded window), which leaves the panel un-transitioned and looking broken.
# Forcing a synchronous reflow with offsetHeight works regardless of paint state.
TOGGLE_JS = (
    "(function(){var t=document.getElementById('blinavToggle'),"
    "p=document.getElementById('blinavPanel'),o=document.getElementById('blinavOverlay'),timer;"
    "if(!t||!p||!o){return;}"
    "function isOpen(){return p.classList.contains('blinav-open');}"
    "function set(open){clearTimeout(timer);"
    "if(open){p.hidden=false;o.hidden=false;void p.offsetHeight;}"
    "p.classList.toggle('blinav-open',open);o.classList.toggle('blinav-open',open);"
    "t.setAttribute('aria-expanded',open?'true':'false');"
    "if(open){var f=p.querySelector('a,button');if(f){f.focus();}}"
    "else{timer=setTimeout(function(){p.hidden=true;o.hidden=true;},300);t.focus();}}"
    "t.addEventListener('click',function(){set(!isOpen());});"
    "o.addEventListener('click',function(){set(false);});"
    "p.addEventListener('click',function(e){if(e.target.closest('.blinav-close')){set(false);}});"
    "document.addEventListener('keydown',function(e){if(e.key==='Escape'&&isOpen()){set(false);}});"
    "})();"
)


def load_cfg():
    with open(NAV_JSON, encoding='utf-8') as f:
        return json.load(f)


def render_block(cfg):
    links = cfg['links']
    phone_href = cfg['phone_href']
    phone = cfg['phone_display']
    quote_href = cfg['quote_href']
    quote = cfg['quote_label']
    brand = cfg['brand']

    footer_items = '\n'.join(
        '      <li><a href="%s">%s</a></li>' % (l['href'], l['label']) for l in links)
    panel_items = '\n'.join(
        '      <li><a href="%s">%s</a></li>' % (l['href'], l['label']) for l in links)

    return '\n'.join([
        START,
        '<nav class="blinav-footer" aria-label="Site">',
        '  <div class="blinav-footer-inner">',
        '    <a class="blinav-brand" href="/">%s</a>' % brand,
        '    <ul class="blinav-footer-links">',
        footer_items,
        '    </ul>',
        '    <div class="blinav-footer-cta">',
        '      <a class="blinav-call" href="%s">%s%s</a>' % (phone_href, ICON_PHONE, phone),
        '      <a class="blinav-quote" href="%s">%s%s</a>' % (quote_href, ICON_BOLT, quote),
        '    </div>',
        '    <p class="blinav-footer-legal">Bill Layne Insurance Agency &middot; 1283 N Bridge St, Elkin, NC 28621 &middot; '
        '<a href="/privacy-policy/">Privacy</a> &middot; <a href="/terms/">Terms</a></p>',
        '  </div>',
        '</nav>',
        '',
        '<div class="blinav-dock-spacer" aria-hidden="true"></div>',
        '<div class="blinav-dock">',
        '  <a class="blinav-dock-btn" href="%s">%sCall</a>' % (phone_href, ICON_PHONE),
        '  <a class="blinav-dock-btn blinav-dock-quote" href="%s">%s%s</a>' % (quote_href, ICON_BOLT, quote),
        '  <button type="button" class="blinav-dock-btn" id="blinavToggle" aria-expanded="false" aria-controls="blinavPanel">%sMenu</button>' % ICON_BARS,
        '</div>',
        '<div class="blinav-overlay" id="blinavOverlay" hidden></div>',
        '<div class="blinav-panel" id="blinavPanel" role="dialog" aria-modal="true" aria-label="Site menu" hidden>',
        '  <div class="blinav-panel-header">',
        '    <span class="blinav-panel-title">%s</span>' % brand,
        '    <button type="button" class="blinav-close" aria-label="Close menu">&times;</button>',
        '  </div>',
        '  <ul class="blinav-panel-links">',
        panel_items,
        '  </ul>',
        '</div>',
        '<script>%s</script>' % TOGGLE_JS,
        END,
    ])


def render_css_link(cfg):
    return '%s<link rel="stylesheet" href="%s?v=%s">%s' % (
        CSS_START, cfg['css_href'], cfg['css_version'], CSS_END)


def transform(src, cfg, rel):
    """Return (new_src, notes) or raise ValueError with a reason."""
    notes = []
    out = src

    # ---- 1. stylesheet link in <head> -------------------------------------
    css_link = render_css_link(cfg)
    if CSS_RE.search(out):
        out, n = CSS_RE.subn(lambda m: css_link, out)
        if n != 1:
            raise ValueError('CSS marker found %d times, expected 1' % n)
        notes.append('css link refreshed')
    else:
        m = re.search(r'</head\s*>', out, re.I)
        if not m:
            raise ValueError('no </head> found')
        if len(re.findall(r'</head\s*>', out, re.I)) != 1:
            raise ValueError('</head> found more than once')
        out = out[:m.start()] + '    ' + css_link + '\n' + out[m.start():]
        notes.append('css link added')

    # ---- 2. the nav block --------------------------------------------------
    block = render_block(cfg)
    if BLOCK_RE.search(out):
        out, n = BLOCK_RE.subn(lambda m: block, out)
        if n != 1:
            raise ValueError('nav marker found %d times, expected 1' % n)
        notes.append('nav block refreshed')
    else:
        m = re.search(r'</body\s*>', out, re.I)
        if not m:
            raise ValueError('no </body> found')
        if len(re.findall(r'</body\s*>', out, re.I)) != 1:
            raise ValueError('</body> found more than once')
        out = out[:m.start()] + block + '\n' + out[m.start():]
        notes.append('nav block added')

    return out, notes


def page_list(cfg, args):
    if args.pages:
        return args.pages
    wave = cfg['waves'].get(str(args.wave))
    if not wave:
        sys.exit('no wave %s in nav.json' % args.wave)
    return wave['pages']


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--apply', action='store_true', help='write changes (default: dry run)')
    ap.add_argument('--check', action='store_true', help='exit 1 if any page is out of date')
    ap.add_argument('--wave', default='1')
    ap.add_argument('--pages', nargs='*', help='explicit page list instead of a wave')
    ap.add_argument('--diff', action='store_true', help='print a unified diff per page')
    args = ap.parse_args()

    cfg = load_cfg()
    pages = page_list(cfg, args)

    changed, failed, same = [], [], []
    for rel in pages:
        path = os.path.join(ROOT, rel.replace('/', os.sep))
        if not os.path.exists(path):
            failed.append((rel, 'file not found'))
            continue
        src = open(path, encoding='utf-8').read()
        try:
            new, notes = transform(src, cfg, rel)
        except ValueError as e:
            failed.append((rel, str(e)))
            continue
        if new == src:
            same.append(rel)
            continue
        changed.append((rel, notes))
        if args.diff:
            d = difflib.unified_diff(src.splitlines(), new.splitlines(),
                                     fromfile=rel, tofile=rel + ' (new)',
                                     lineterm='', n=2)
            print('\n'.join(d))
            print()
        if args.apply:
            with open(path, 'w', encoding='utf-8', newline='') as f:
                f.write(new)

    verb = 'updated' if args.apply else 'would change'
    print('%s: %d' % (verb, len(changed)))
    for rel, notes in changed:
        print('   %-56s %s' % (rel, ', '.join(notes)))
    if same:
        print('already current: %d' % len(same))
        for rel in same:
            print('   %s' % rel)
    if failed:
        print('FAILED: %d' % len(failed))
        for rel, why in failed:
            print('   %-56s %s' % (rel, why))
    if not args.apply and not args.check:
        print('\n(dry run - nothing written. add --apply to write, --diff to see changes)')
    if args.check and (changed or failed):
        sys.exit(1)
    if failed:
        sys.exit(2)


if __name__ == '__main__':
    main()
