#!/usr/bin/env python3
"""
build-nav.py - keep every page's site menu identical to the homepage.

Source of truth:  tools/nav.json
Styles (standalone mode only): css/bli-nav.css

Two modes, chosen per wave in nav.json:

  standalone  For pages with NO site menu. Injects a self-contained footer nav
              + mobile dock between
                  <!-- BLI-NAV:START ... -->   ...   <!-- BLI-NAV:END -->
              plus one marked <link> in <head>. Re-runs replace in place.

  families    For pages that already carry one of the site's menu containers.
              Only the LINK ITEMS inside each container are re-rendered, in
              canonical order, using that family's own item markup; the
              wrapper, its classes, header and CTA are untouched. Families:
                #mobileDockPanel / #menuPanel  -> <ul class="menu-links">
                #menu-drawer                   -> <div class="... overflow-y-auto ...">
                #navigation-menu               -> <nav class="space-y-4">
                #mobile-menu                   -> <nav class="navbar-menu-nav">
              A container whose list cannot be located is reported and the
              page is left untouched.

Usage
    python tools/build-nav.py --wave 1              # dry run, summary
    python tools/build-nav.py --wave 2 --diff       # dry run with unified diffs
    python tools/build-nav.py --wave 2 --apply      # write
    python tools/build-nav.py --wave 2 --pages a.html b.html --apply
    python tools/build-nav.py --wave 2 --check      # exit 1 if anything is out of date

Every substitution asserts it matched exactly once; on any mismatch the file is
left untouched and reported as FAILED. This repo is the live site - read the
diff before you --apply.
"""

import argparse
import difflib
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NAV_JSON = os.path.join(ROOT, 'tools', 'nav.json')

# ---------------------------------------------------------------------------
# standalone block
# ---------------------------------------------------------------------------
START = '<!-- BLI-NAV:START - generated by tools/build-nav.py from tools/nav.json. Do not edit by hand. -->'
END = '<!-- BLI-NAV:END -->'
CSS_START = '<!-- BLI-NAV-CSS:START -->'
CSS_END = '<!-- BLI-NAV-CSS:END -->'
BLOCK_RE = re.compile(re.escape(START) + r'.*?' + re.escape(END), re.S)
CSS_RE = re.compile(re.escape(CSS_START) + r'.*?' + re.escape(CSS_END), re.S)

ICON_PHONE = ('<svg viewBox="0 0 512 512" aria-hidden="true"><path d="M497.4 361.8l-112-48a24 24 0 0 0-28 6.9l-49.6 60.6A370.7 370.7 0 0 1 130.6 204.1l60.6-49.6a23.9 23.9 0 0 0 6.9-28l-48-112A24.2 24.2 0 0 0 122.6.6l-104 24A24 24 0 0 0 0 48c0 256.5 207.9 464 464 464a24 24 0 0 0 23.4-18.6l24-104a24.3 24.3 0 0 0-14-27.6z"/></svg>')
ICON_BOLT = ('<svg viewBox="0 0 320 512" aria-hidden="true"><path d="M296 160H180.6l42.6-129.8C227.2 17.9 218.1 0 204.2 0H96c-9.8 0-18.2 7.1-19.8 16.8l-48 288C26.2 316.8 35.4 328 47.6 328h118.7L119 480.2c-3.8 12.3 5.5 24 18.3 24 6.8 0 13.3-3.5 16.9-9.8l160-272c9.3-15.9-2.2-35.9-18.2-35.9z"/></svg>')
ICON_BARS = ('<svg viewBox="0 0 448 512" aria-hidden="true"><path d="M16 132h416c8.8 0 16-7.2 16-16V76c0-8.8-7.2-16-16-16H16C7.2 60 0 67.2 0 76v40c0 8.8 7.2 16 16 16zm0 160h416c8.8 0 16-7.2 16-16v-40c0-8.8-7.2-16-16-16H16c-8.8 0-16 7.2-16 16v40c0 8.8 7.2 16 16 16zm0 160h416c8.8 0 16-7.2 16-16v-40c0-8.8-7.2-16-16-16H16c-8.8 0-16 7.2-16 16v40c0 8.8 7.2 16 16 16z"/></svg>')

# Deliberately does NOT use requestAnimationFrame to kick off the transition:
# rAF does not fire while the page is not being painted (background tab, an
# occluded window), which leaves the panel un-transitioned and looking broken.
# Forcing a synchronous reflow with offsetHeight works regardless of paint state.
TOGGLE_JS = (
    "(function(){var t=document.getElementById('blinavToggle'),"
    "p=document.getElementById('blinavPanel'),o=document.getElementById('blinavOverlay'),timer;"
    "if(!t||!p||!o){return;}"
    "function isOpen(){return p.classList.contains('blinav-open');}"
    "function set(open){clearTimeout(timer);"
    "if(open){p.hidden=false;o.hidden=false;void p.offsetHeight;}"
    "p.classList.toggle('blinav-open',open);o.classList.toggle('blinav-open',open);"
    "t.setAttribute('aria-expanded',open?'true':'false');"
    "if(open){var f=p.querySelector('a,button');if(f){f.focus();}}"
    "else{timer=setTimeout(function(){p.hidden=true;o.hidden=true;},300);t.focus();}}"
    "t.addEventListener('click',function(){set(!isOpen());});"
    "o.addEventListener('click',function(){set(false);});"
    "p.addEventListener('click',function(e){if(e.target.closest('.blinav-close')){set(false);}});"
    "document.addEventListener('keydown',function(e){if(e.key==='Escape'&&isOpen()){set(false);}});"
    "})();"
)


def render_block(cfg):
    links = cfg['links']
    items = '\n'.join('      <li><a href="%s">%s</a></li>' % (l['href'], l['label']) for l in links)
    return '\n'.join([
        START,
        '<nav class="blinav-footer" aria-label="Site">',
        '  <div class="blinav-footer-inner">',
        '    <a class="blinav-brand" href="/">%s</a>' % cfg['brand'],
        '    <ul class="blinav-footer-links">',
        items,
        '    </ul>',
        '    <div class="blinav-footer-cta">',
        '      <a class="blinav-call" href="%s">%s%s</a>' % (cfg['phone_href'], ICON_PHONE, cfg['phone_display']),
        '      <a class="blinav-quote" href="%s">%s%s</a>' % (cfg['quote_href'], ICON_BOLT, cfg['quote_label']),
        '    </div>',
        '    <p class="blinav-footer-legal">Bill Layne Insurance Agency &middot; 1283 N Bridge St, Elkin, NC 28621 &middot; '
        '<a href="/privacy-policy/">Privacy</a> &middot; <a href="/terms/">Terms</a></p>',
        '  </div>',
        '</nav>',
        '',
        '<div class="blinav-dock-spacer" aria-hidden="true"></div>',
        '<div class="blinav-dock">',
        '  <a class="blinav-dock-btn" href="%s">%sCall</a>' % (cfg['phone_href'], ICON_PHONE),
        '  <a class="blinav-dock-btn blinav-dock-quote" href="%s">%s%s</a>' % (cfg['quote_href'], ICON_BOLT, cfg['quote_label']),
        '  <button type="button" class="blinav-dock-btn" id="blinavToggle" aria-expanded="false" aria-controls="blinavPanel">%sMenu</button>' % ICON_BARS,
        '</div>',
        '<div class="blinav-overlay" id="blinavOverlay" hidden></div>',
        '<div class="blinav-panel" id="blinavPanel" role="dialog" aria-modal="true" aria-label="Site menu" hidden>',
        '  <div class="blinav-panel-header">',
        '    <span class="blinav-panel-title">%s</span>' % cfg['brand'],
        '    <button type="button" class="blinav-close" aria-label="Close menu">&times;</button>',
        '  </div>',
        '  <ul class="blinav-panel-links">',
        items,
        '  </ul>',
        '</div>',
        '<script>%s</script>' % TOGGLE_JS,
        END,
    ])


def render_css_link(cfg):
    return '%s<link rel="stylesheet" href="%s?v=%s">%s' % (CSS_START, cfg['css_href'], cfg['css_version'], CSS_END)


def transform_standalone(src, cfg, rel):
    notes = []
    out = src
    css_link = render_css_link(cfg)
    if CSS_RE.search(out):
        out, n = CSS_RE.subn(lambda m: css_link, out)
        if n != 1:
            raise ValueError('CSS marker found %d times, expected 1' % n)
        notes.append('css link refreshed')
    else:
        heads = list(re.finditer(r'</head\s*>', out, re.I))
        if len(heads) != 1:
            raise ValueError('</head> found %d times' % len(heads))
        m = heads[0]
        out = out[:m.start()] + '    ' + css_link + '\n' + out[m.start():]
        notes.append('css link added')

    block = render_block(cfg)
    if BLOCK_RE.search(out):
        out, n = BLOCK_RE.subn(lambda m: block, out)
        if n != 1:
            raise ValueError('nav marker found %d times, expected 1' % n)
        notes.append('nav block refreshed')
    else:
        bodies = list(re.finditer(r'</body\s*>', out, re.I))
        if len(bodies) != 1:
            raise ValueError('</body> found %d times' % len(bodies))
        m = bodies[0]
        out = out[:m.start()] + block + '\n' + out[m.start():]
        notes.append('nav block added')
    return out, notes


# ---------------------------------------------------------------------------
# minimal balanced-tag scanner (no external deps)
# ---------------------------------------------------------------------------
TAG = re.compile(r'<(/?)([a-zA-Z][a-zA-Z0-9-]*)((?:"[^"]*"|\'[^\']*\'|[^>"\'])*?)(/?)>', re.S)
VOID = {'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link',
        'meta', 'param', 'source', 'track', 'wbr'}
ATTR = re.compile(r'([a-zA-Z-]+)\s*=\s*"([^"]*)"|([a-zA-Z-]+)\s*=\s*\'([^\']*)\'')


def attrs_of(attr_str):
    d = {}
    for m in ATTR.finditer(attr_str):
        if m.group(1):
            d[m.group(1).lower()] = m.group(2)
        else:
            d[m.group(3).lower()] = m.group(4)
    return d


def find_element(s, names, pred, start=0):
    """First balanced element with tag in `names` whose attrs satisfy `pred`.
    Returns (open_end, close_start, attrs) - the inner HTML is s[open_end:close_start]."""
    names = {n.lower() for n in names}
    toks = [m for m in TAG.finditer(s, start)]
    for i, m in enumerate(toks):
        closing, name, attr_str, self_close = m.group(1), m.group(2).lower(), m.group(3), m.group(4)
        if closing or name not in names or name in VOID or self_close:
            continue
        a = attrs_of(attr_str)
        if not pred(a):
            continue
        depth = 1
        for j in range(i + 1, len(toks)):
            m2 = toks[j]
            if m2.group(2).lower() != name:
                continue
            if m2.group(1):
                depth -= 1
                if depth == 0:
                    return m.end(), m2.start(), a
            elif not m2.group(4):
                depth += 1
        raise ValueError('unbalanced <%s>' % name)
    return None


# ---------------------------------------------------------------------------
# family renderers - item markup copied from the real pages (dock: any
# mobileDockPanel page; drawer: index.html; navigation-menu: carrier pages;
# mobile-menu: auto-center/coverage-comparison.html)
# ---------------------------------------------------------------------------
def page_href(rel):
    """Canonical href for a page path, so the drawer can mark it active."""
    h = '/' + rel.replace(os.sep, '/')
    h = re.sub(r'/index\.html$', '/', h)
    h = re.sub(r'\.html$', '', h)
    return '/' if h == '/index' else h


def items_dock(cfg, rel, indent):
    out = []
    for l in cfg['links']:
        out.append('%s<li><a href="%s"><span class="menu-icon %s"><i class="fas %s"></i></span> %s '
                   '<i class="fas fa-chevron-right menu-arrow"></i></a></li>'
                   % (indent, l['href'], l['dock'], l['icon'], l['label']))
    return '\n' + '\n'.join(out) + '\n' + indent[:-4]


def items_drawer(cfg, rel, indent):
    cur = page_href(rel)
    out = []
    for l in cfg['links']:
        tw = l['tw']
        if l['href'] == cur:
            # active item - same treatment the homepage gives "Home"
            a_cls = 'group block p-2.5 rounded-xl bg-primary-50 text-primary-700 font-bold flex items-center gap-3'
            tile = 'w-7 h-7 rounded-lg bg-white flex items-center justify-center text-primary-600 shadow-sm'
        else:
            a_cls = ('group block p-2.5 rounded-xl %s font-bold flex items-center gap-3 transition-colors'
                     % l.get('tw_a', 'hover:bg-slate-50 text-slate-600'))
            tile = ('w-7 h-7 rounded-lg %s flex items-center justify-center text-%s-500 '
                    'group-hover:scale-110 transition-transform' % (l.get('tw_tile', 'bg-%s-50' % tw), tw))
        out.append('%s<a href="%s" class="%s"><div class="%s"><i class="fas %s"></i></div> %s</a>'
                   % (indent, l['href'], a_cls, tile, l['icon'], l['label']))
    return '\n' + '\n'.join(out) + '\n' + indent[:-4]


def items_navmenu(cfg, rel, indent):
    out = []
    for l in cfg['links']:
        out.append('%s<a href="%s" class="block py-3 px-2 text-gray-700 hover:text-blue-600 hover:bg-blue-50 '
                   'font-medium border-b border-gray-200 rounded transition-all">\n%s    <i class="fas %s mr-3 w-5"></i>%s\n%s</a>'
                   % (indent, l['href'], indent, l['icon'], l['label'], indent))
    return '\n' + '\n'.join(out) + '\n' + indent[:-4]


def items_mobilemenu(cfg, rel, indent):
    out = ['%s<a href="%s" class="nav-link">%s</a>' % (indent, l['href'], l['label']) for l in cfg['links']]
    return '\n' + '\n'.join(out) + '\n' + indent[:-4]


FAMILIES = [
    # (container ids, list tag, list predicate, renderer, note)
    (('mobileDockPanel', 'menuPanel'), ('ul',), lambda a: 'menu-links' in a.get('class', ''), items_dock, 'dock'),
    (('menu-drawer',), ('div',), lambda a: 'overflow-y-auto' in a.get('class', ''), items_drawer, 'drawer'),
    (('navigation-menu',), ('nav',), lambda a: True, items_navmenu, 'navigation-menu'),
    (('mobile-menu',), ('nav',), lambda a: 'navbar-menu-nav' in a.get('class', ''), items_mobilemenu, 'mobile-menu'),
]


def indent_of(s, pos):
    """Leading whitespace of the first non-blank line at/after pos, plus 4."""
    m = re.search(r'\n([ \t]*)\S', s[pos:pos + 400])
    return (m.group(1) if m else '        ')


def transform_families(src, cfg, rel):
    out = src
    notes = []
    for ids, list_tags, pred, renderer, note in FAMILIES:
        for cid in ids:
            if ('id="%s"' % cid) not in out:
                continue
            found = find_element(out, ['div', 'nav', 'ul'], lambda a: a.get('id') == cid)
            if not found:
                raise ValueError('#%s present but not parseable' % cid)
            c_open, c_close, _ = found
            inner = out[c_open:c_close]
            lst = find_element(inner, list_tags, pred)
            if not lst:
                # #mobile-menu has two known shapes. The <nav class="navbar-menu-nav">
                # form is handled here; the Tailwind form on the old #main-header
                # town/guide pages belongs to wave 3, so skip it and keep going.
                if cid == 'mobile-menu':
                    notes.append('mobile-menu skipped (wave 3 structure)')
                    continue
                raise ValueError('#%s: item list not found' % cid)
            l_open, l_close, _ = lst
            # the current items' indentation, so the diff stays readable
            first_item = re.search(r'\n([ \t]*)<(li|a)\b', inner[l_open:l_close])
            indent = first_item.group(1) if first_item else indent_of(inner, l_open)
            new_items = renderer(cfg, rel, indent)
            abs_open, abs_close = c_open + l_open, c_open + l_close
            if out[abs_open:abs_close] != new_items:
                out = out[:abs_open] + new_items + out[abs_close:]
                notes.append(note)
    if not notes and not any(('id="%s"' % cid) in src for ids, *_ in FAMILIES for cid in ids):
        raise ValueError('no family container on this page')
    return out, notes


# ---------------------------------------------------------------------------
def load_cfg():
    with open(NAV_JSON, encoding='utf-8') as f:
        return json.load(f)


def discover_family_pages(cfg):
    ids = [cid for ids, *_ in FAMILIES for cid in ids]
    skip_dirs = {'.git', 'node_modules', '.claude', 'output', '__pycache__', '.playwright-cli',
                 '_ul-MSI', 'vendor', 'fonts', 'css', 'js', 'data', 'email-assets', 'functions',
                 'ds-bundle', 'templates', 'tools', 'Blog Folders stored'}
    found = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in skip_dirs and not d.startswith('.')]
        rel_dir = os.path.relpath(dirpath, ROOT).replace(os.sep, '/')
        if rel_dir.startswith('blog/blogs'):
            continue
        for fn in filenames:
            if not fn.endswith('.html'):
                continue
            rel = fn if rel_dir == '.' else rel_dir + '/' + fn
            if rel in cfg.get('exclude', []):
                continue
            try:
                s = open(os.path.join(dirpath, fn), encoding='utf-8').read()
            except UnicodeDecodeError:
                continue
            if any(('id="%s"' % cid) in s for cid in ids):
                found.append(rel)
    return sorted(found)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--wave', default='1')
    ap.add_argument('--pages', nargs='*')
    ap.add_argument('--apply', action='store_true')
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--diff', action='store_true')
    args = ap.parse_args()

    cfg = load_cfg()
    wave = cfg['waves'].get(args.wave)
    if not wave:
        sys.exit('no wave %r in nav.json' % args.wave)
    mode = wave.get('mode', 'standalone')
    transform = transform_standalone if mode == 'standalone' else transform_families
    if args.pages:
        pages = args.pages
    elif wave['pages'] == 'auto':
        pages = discover_family_pages(cfg)
    else:
        pages = wave['pages']
    pages = [p for p in pages if p not in cfg.get('exclude', [])]

    changed, failed, same = [], [], []
    for rel in pages:
        path = os.path.join(ROOT, rel.replace('/', os.sep))
        if not os.path.exists(path):
            failed.append((rel, 'file not found'))
            continue
        src = open(path, encoding='utf-8').read()
        try:
            new, notes = transform(src, cfg, rel)
        except ValueError as e:
            failed.append((rel, str(e)))
            continue
        if new == src:
            same.append(rel)
            continue
        changed.append((rel, notes))
        if args.diff:
            print('\n'.join(difflib.unified_diff(src.splitlines(), new.splitlines(),
                                                 fromfile=rel, tofile=rel + ' (new)', lineterm='', n=1)))
            print()
        if args.apply:
            with open(path, 'w', encoding='utf-8', newline='') as f:
                f.write(new)

    print('wave %s (%s) - %d pages' % (args.wave, mode, len(pages)))
    print('%s: %d' % ('updated' if args.apply else 'would change', len(changed)))
    for rel, notes in changed:
        print('   %-60s %s' % (rel, ', '.join(notes)))
    if same:
        print('already current: %d' % len(same))
        if len(same) <= 30:
            for rel in same:
                print('   %s' % rel)
    if failed:
        print('FAILED (left untouched): %d' % len(failed))
        for rel, why in failed:
            print('   %-60s %s' % (rel, why))
    if not args.apply and not args.check:
        print('\n(dry run - nothing written. --apply to write, --diff to see changes)')
    if args.check and (changed or failed):
        sys.exit(1)
    if failed:
        sys.exit(2)


if __name__ == '__main__':
    main()
