#!/usr/bin/env python3
"""Build sitemap.xml (a sitemap INDEX) plus sitemap-pages.xml and sitemap-blog.xml
from the HTML files that are actually in the repo.

Rules (Google Search Central, Sept 2026):
  * only canonical, indexable, 200-status URLs are listed
  * <lastmod> only, no <priority>/<changefreq> (Google ignores both)
  * lastmod = the last git commit that touched the file, so it only moves when
    the page really changed
  * a page is skipped when it has no <link rel="canonical">, when its canonical
    points somewhere else, when it carries a noindex robots tag, or when it is a
    redirect stub (meta refresh) / has a redirect function in functions/
  * sitemap-images.xml is hand-maintained and simply referenced by the index

Run after adding or removing pages:   python tools/build-sitemaps.py
Check without writing:                python tools/build-sitemaps.py --check
"""
import os
import re
import subprocess
import sys
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = 'https://www.billlayneinsurance.com'
SKIP_PREFIXES = ('templates/', 'shared/', 'auto-quote-template/', 'Insurance-Contact-Information-main/',
                 'blog/blog-template', 'blog/sample-blog-post', 'quotes-customer/', '_')
SKIP_FILES = {'404.html'}


def sh(*args):
    return subprocess.run(args, capture_output=True, text=True, cwd=ROOT).stdout


def tracked_html():
    for f in sh('git', 'ls-files', '*.html').split('\n'):
        f = f.strip()
        if not f or f.startswith('.claude') or f in SKIP_FILES or f.startswith(SKIP_PREFIXES):
            continue
        yield f


def lastmod(path):
    d = sh('git', 'log', '-1', '--format=%cs', '--', path).strip()
    if not d:
        d = date.today().isoformat()   # not committed yet
    return d


def redirect_functions():
    """URLs that now 301 via functions/ (generated by tools/gen-redirect-functions.py)."""
    urls = set()
    fdir = os.path.join(ROOT, 'functions')
    for dirpath, _dirs, files in os.walk(fdir):
        for name in files:
            if not name.endswith('.js'):
                continue
            rel = os.path.relpath(os.path.join(dirpath, name), fdir).replace('\\', '/')
            if name == '[[path]].js':
                urls.add('/' + os.path.dirname(rel) + '/')
            elif name.endswith('.html.js'):
                urls.add('/' + rel[:-3])
            else:
                urls.add('/' + rel[:-3])
    # Exact (non-wildcard) rules in _redirects redirect too.
    with open(os.path.join(ROOT, '_redirects'), encoding='utf-8') as fh:
        for line in fh:
            parts = line.split()
            if len(parts) >= 2 and not parts[0].startswith('#') and '*' not in parts[0]:
                urls.add(parts[0])
    return urls


def classify(path):
    with open(os.path.join(ROOT, path), encoding='utf-8', errors='replace') as fh:
        head = fh.read(60000)
    if re.search(r'http-equiv="refresh"', head, re.I):
        return None, 'stub'
    m = re.search(r'<link[^>]+rel="canonical"[^>]+href="([^"]*)"', head, re.I) or \
        re.search(r'<link[^>]+href="([^"]*)"[^>]+rel="canonical"', head, re.I)
    if not m:
        return None, 'no canonical'
    canon = m.group(1).strip()
    r = re.search(r'<meta[^>]+name="robots"[^>]+content="([^"]*)"', head, re.I) or \
        re.search(r'<meta[^>]+content="([^"]*)"[^>]+name="robots"', head, re.I)
    if r and 'noindex' in r.group(1).lower():
        return None, 'noindex'
    # expected URL for this file
    if path == 'index.html':
        url = BASE + '/'
    elif path.endswith('/index.html'):
        url = BASE + '/' + path[:-len('index.html')]
    else:
        url = BASE + '/' + path[:-5]
    if canon != url:
        return None, f'canonical elsewhere ({canon})'
    return url, 'ok'


def build():
    redirected = redirect_functions()
    pages, blog, skipped = [], [], {}
    for f in tracked_html():
        url, why = classify(f)
        if not url:
            skipped.setdefault(why.split(' (')[0], []).append(f)
            continue
        if url[len(BASE):] in redirected:
            skipped.setdefault('redirect function', []).append(f)
            continue
        entry = (url, lastmod(f))
        (blog if f.startswith('blog/blogs/') else pages).append(entry)
    pages.sort()
    blog.sort()
    return pages, blog, skipped


def urlset(entries):
    body = '\n'.join(f'  <url>\n    <loc>{u}</loc>\n    <lastmod>{d}</lastmod>\n  </url>' for u, d in entries)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + body + '\n</urlset>\n')


def index(children):
    body = '\n'.join(f'  <sitemap>\n    <loc>{BASE}/{name}</loc>\n    <lastmod>{d}</lastmod>\n  </sitemap>' for name, d in children)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + body + '\n</sitemapindex>\n')


def main():
    check = '--check' in sys.argv
    pages, blog, skipped = build()
    today = date.today().isoformat()
    img_mod = lastmod('sitemap-images.xml')
    files = {
        'sitemap-pages.xml': urlset(pages),
        'sitemap-blog.xml': urlset(blog),
        'sitemap.xml': index([('sitemap-pages.xml', max(d for _u, d in pages)),
                              ('sitemap-blog.xml', max(d for _u, d in blog)),
                              ('sitemap-images.xml', img_mod)]),
    }
    print(f'pages {len(pages)}  blog {len(blog)}  (index dated {today})')
    for why, lst in sorted(skipped.items()):
        print(f'  skipped {len(lst):4d} {why}')
        if why in ('no canonical', 'canonical elsewhere'):
            for f in lst[:40]:
                print('        ' + f)
    if check:
        return
    for name, content in files.items():
        with open(os.path.join(ROOT, name), 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(content)
    print('wrote sitemap.xml, sitemap-pages.xml, sitemap-blog.xml')


if __name__ == '__main__':
    main()
