#!/usr/bin/env python3
"""Generate Cloudflare Pages Functions that serve edge 301s for legacy URLs.

Why this exists: the project's `_redirects` file only honours its first 100
rules (verified live 2026-08-17) and is full. Pages Functions have no such cap
and are only invoked for the exact paths they are named for, so every legacy
URL that used to be a meta-refresh HTML stub gets a tiny function instead.

Routing facts (tested with `wrangler pages dev` 2026-09-02):
  functions/foo.js             -> /foo  AND /foo/
  functions/foo.html.js        -> /foo.html
  functions/foo/[[path]].js    -> /foo, /foo/, /foo/anything

Source of truth: tools/legacy-redirects.json  { "/from": "/to", ... }
  * "/from" without a trailing slash  -> functions/from.js + functions/from.html.js
  * "/from/" with a trailing slash    -> functions/from/[[path]].js
Run:  python tools/gen-redirect-functions.py            (writes files)
      python tools/gen-redirect-functions.py --check    (dry run, lists output)
Regenerate after every edit to the JSON. Never hand-edit the generated files.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAP = os.path.join(ROOT, 'tools', 'legacy-redirects.json')
FUNCS = os.path.join(ROOT, 'functions')
MARK = '// GENERATED by tools/gen-redirect-functions.py'

TEMPLATE = '''%(mark)s from tools/legacy-redirects.json - do not edit by hand.
// Legacy URL %(frm)s -> %(to)s (edge 301; replaces the old meta-refresh stub).
const TO = %(to_json)s;
export function onRequest({ request, next }) {
  const url = new URL(request.url);
  // A function route also matches its trailing-slash twin. If that twin IS the
  // destination (e.g. /contact-us -> /contact-us/), serve the real page.
  if (url.pathname === TO) return next();
  return Response.redirect(new URL(TO + url.search, url.origin).toString(), 301);
}
'''


def target_files(frm):
    frm = frm.strip()
    if frm.endswith('/'):
        return [os.path.join(FUNCS, frm.strip('/'), '[[path]].js')]
    base = frm.strip('/')
    return [os.path.join(FUNCS, base + '.js'), os.path.join(FUNCS, base + '.html.js')]


def main():
    check = '--check' in sys.argv
    with open(MAP, encoding='utf-8') as fh:
        mapping = json.load(fh)
    # Remove previously generated files so deletions in the JSON take effect.
    stale = []
    for dirpath, _dirs, files in os.walk(FUNCS):
        for name in files:
            path = os.path.join(dirpath, name)
            try:
                with open(path, encoding='utf-8') as fh:
                    head = fh.read(len(MARK))
            except OSError:
                continue
            if head == MARK:
                stale.append(path)
    written = []
    for frm, to in mapping.items():
        if not frm.startswith('/') or not to.startswith('/'):
            sys.exit(f'bad entry {frm!r} -> {to!r}: both must start with /')
        if frm.rstrip('/') == to.rstrip('/') and frm != to and not frm.endswith('/'):
            pass  # /x -> /x/ is legitimate (guarded in the template)
        elif frm == to:
            sys.exit(f'self-redirect {frm}')
        for path in target_files(frm):
            body = TEMPLATE % {'mark': MARK, 'frm': frm, 'to': to, 'to_json': json.dumps(to)}
            written.append(path)
            if check:
                continue
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, 'w', encoding='utf-8', newline='\n') as fh:
                fh.write(body)
    if not check:
        for path in stale:
            if path not in written:
                os.remove(path)
        # prune empty dirs left behind
        for dirpath, dirs, files in os.walk(FUNCS, topdown=False):
            if dirpath != FUNCS and not dirs and not files:
                os.rmdir(dirpath)
    rel = sorted(os.path.relpath(p, ROOT).replace('\\', '/') for p in written)
    print(f'{"would write" if check else "wrote"} {len(rel)} function files for {len(mapping)} legacy URLs')
    for r in rel:
        print('  ' + r)
    removed = [p for p in stale if p not in written]
    if removed:
        print(f'{"would remove" if check else "removed"} {len(removed)} stale generated files')


if __name__ == '__main__':
    main()
